# Server port
server.port=8080

# MySQL datasource
spring.datasource.url=mysql://root:FhDTWFHtgcBOGtWrpEwdgoMYQpeolArD@shinkansen.proxy.rlwy.net:19273/railway
spring.datasource.username=root
spring.datasource.password=FhDTWFHtgcBOGtWrpEwdgoMYQpeolArD

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
file.upload-dir=uploads

# JWT secret
app.jwt.secret=nLkPvZ3CJMb2pZVZ6oWRqF2u3Tt0tV8J5c71v0Z5XgA=

# Email Configuration (Gmail SMTP - SSL)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=saibittu594@gmail.com
spring.mail.password=zsxr jcis fzym epyq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

